timestamp: 2025-08-08 13:50:00 +1
epgsources:
  - url: https://github.com/KODIKAS-NL/GreekTv-epg/releases/download/EPG/epg.xml
    compression: none
channels:
  - id: ert1
    title: Ert 1
    epgId: ert1
    order: 1
    logoUrl: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/logos/ert1.png
    pipeline:
      - type: url
        param: http://195.226.218.163/vid/ert1/playlist.m3u8
  - id: ert2
    title: Ert 2
    epgId: ert2
    order: 2
    logoUrl: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/logos/ert2.png
    pipeline:
      - type: url
        param: http://192.168.1.52:10808/aHR0cHM6Ly9lcnRmbGl4LWdyZWVjZS5zaWxpY29ud2ViLmNvbS9tcGVndHMvNjE4NjE4XzIzNDE1NTcvbWFzdGVyX21wZWd0cy5tM3U4.m3u8
  - id: ert3
    title: Ert 3
    epgId: ert3
    order: 3
    logoUrl: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/logos/ert3.png
    pipeline:
      - type: url
        param: http://192.168.1.52:10808/aHR0cHM6Ly9lcnRmbGl4LWdyZWVjZS5zaWxpY29ud2ViLmNvbS9tcGVndHMvNjE4NjE4XzIzNDE1NjAvbWFzdGVyX21wZWd0cy5tM3U4.m3u8
  - id: skai
    title: Skai
    epgId: skai
    order: 4
    logoUrl: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/logos/skai.png
    pipeline:
      - type: url
        param: https://skai-live.siliconweb.com/media/cambria4/index.m3u8
  - id: alpha
    title: Alpha
    epgId: alpha
    order: 5
    logoUrl: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/logos/alpha.png
    pipeline:
      - type: url
        param: https://www.alphatv.gr/webtv/live
      - type: source
      - type: regex
        param: https:\/\/.*m3u8
  - id: ant1
    title: Ant1
    epgId: ant1
    order: 6
    logoUrl: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/logos/ant1.png
    pipeline:
      - type: url
        param: https://mcdn.antennaplus.gr/live/media0/Ant1/HLS/Ant1.m3u8
  - id: mega
    title: mega
    epgId: mega
    order: 7
    logoUrl: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/logos/mega_outline.png
    pipeline:
      - type: url
        param: https://raw.githubusercontent.com/jimgate07/grtv/refs/heads/master/Metadoseis/mega.m3u8
  - id: ertworld
    title: Ert World
    epgId: ertworld
    order: 8
    logoUrl: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/logos/ertworld.png
    pipeline:
      - type: url
        param: https://ertflix.akamaized.net/ertlive/ertworld/default/index.m3u8
  - id: star
    title: Star
    epgId: star
    order: 9
    logoUrl: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/logos/star.jpg
    pipeline:
      - type: url
        param: https://www.star.gr/tv/live-stream/
      - type: source
      - type: regex
        param: https:.*\.m3u8
  - id: opentv
    title: opentv
    epgId: open
    order: 10
    logoUrl: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/logos/open_outline.png
    pipeline:
      - type: url
        param: https://liveopen.siliconweb.com/openTvLive/liveopen/playlist.m3u8
  - id: m.tv
    title: MacedoniaTV
    epgId: mtv
    order: 11
    logoUrl: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/logos/mak.png
    pipeline:
      - type: url
        param: https://mcdn.antennaplus.gr/live/media0/MAK/HLS/MAK.m3u8
  - id: ert_news
    title: Ert News
    epgId: ertnews
    order: 12
    logoUrl: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/logos/ert_news.png
    pipeline:
      - type: url
        param: https://ertflix.akamaized.net/ertlive/ertnews/default/index.m3u8
  - id: riksat
    title: RikSat
    epgId: RIKsat.cy
    order: 13
    logoUrl: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/logos/riksat.png
    pipeline:
      - type: url
        param: https://l3.cloudskep.com/cybcsat/abr/playlist.m3u8
  - id: rik1
    title: Rik1
    epgId: rik1
    order: 14
    logoUrl: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/logos/rik1.png
    pipeline:
      - type: url
        param: http://31.121.110.30:4000/play/a023/index.m3u8
  - id: rik2
    title: Rik2
    epgId: rik2
    order: 15
    logoUrl: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/logos/rik2.png
    pipeline:
      - type: url
        param: http://31.121.110.30:4000/play/a024/index.m3u8
  - id: bluesky
    title: BlueSky
    epgId: bluesky
    order: 16
    logoUrl: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/logos/bluesky.png
    pipeline:
      - type: url
        param: https://blueskytv.gr/live-tv/
      - type: source
      - type: css
        param:
          query: ".svpPlayer"
          selector:
            type: attribute
            value: data-props
      - type: json
        param: "data.src"
  - id: euronews
    title: EuroNews
    epgId: EuroNews
    order: 17
    logoUrl: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/logos/euronews.png
    pipeline:
      - type: url
        param: https://gr.euronews.com/live
      - type: source
      - type: css
        param:
          query: .u-aspect-ratio-16x9
          selector:
            type: attribute
            value: data-video
      - type: json
        param: videoId
      - type: youtubeid
  - id: kontra
    title: Kontra
    epgId: kontra
    order: 18
    logoUrl: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/logos/kontra.png
    pipeline:
      - type: url
        param: https://kontralive.siliconweb.com/live/kontratv/playlist.m3u8