timestamp: 2023-01-03 20:46:00 +1
epgsources:
  - url: https://github.com/KODIKAS-NL/GreekTv-epg/releases/download/EPG/epg.xml
    compression: none
channels:
  - id: ert1
    title: Ert 1
    epgId: ert1
    pipeline:
      - type: url
        param: https://cbd537474fbad4634b64787657ff6456.msvdn.net/ert1/ert_ev1_main/mainabr/playlist_dvr.m3u8?proxy
  - id: ert2
    title: Ert 2
    epgId: ert2
    pipeline:
      - type: url
        param: https://cbd537474fbad4634b64787657ff6456.msvdn.net/ert2/ert_ev2_main/mainabr/playlist_dvr.m3u8?proxy
  - id: ert3
    title: Ert 3
    epgId: ert3
    pipeline:
      - type: url
        param: https://cbd537474fbad4634b64787657ff6456.msvdn.net/ert3/ert_ev3_main/mainabr/playlist_dvr.m3u8?proxy
  - id: skai
    title: Skai
    epgId: skai
    pipeline:
      - type: url
        param: https://skai-live.siliconweb.com/media/cambria4/index.m3u8
  - id: alpha
    title: Alpha
    epgId: alpha
    pipeline:
      - type: url
        param: https://www.alphatv.gr/webtv/live
      - type: source
      - type: regex
        param: https:\/\/.*m3u8
  - id: ant1
    title: Ant1
    epgId: ant1
    pipeline:
      - type: url
        param: http://95.107.132.106/out/u/atsykmssuyrsyhth.m3u8
  - id: mega
    title: mega
    epgId: mega
    pipeline:
      - type: url
        param: https://streamcdnh2-c98db5952cb54b358365984178fb898a.msvdn.net/live/S86713049/gonOwuUacAxM/playlist.m3u8
  - id: ertworld
    title: Ert World
    epgId: ertworld
    pipeline:
      - type: url
        param: https://cbd537474fbad4634b64787657ff6456.msvdn.net/ertworld/ert_world_main/mainabr/playlist_dvr.m3u8
  - id: star
    title: Star
    epgId: star
    pipeline:
      - type: url
        param: https://www.star.gr/tv/live-stream/
      - type: source
      - type: regex
        param: https:.*\.m3u8
  - id: opentv
    title: opentv
    epgId: open
    pipeline:
      - type: url
        param: https://liveopencloud.siliconweb.com/1/ZlRza2R6L2tFRnFJ/eWVLSlQx/hls/live/playlist.m3u8
  - id: m.tv
    title: MacedoniaTV
    epgId: mtv
    pipeline:
      - type: url
        param: https://raw.githubusercontent.com/KODIKAS-NL/GreekTv.Resources/main/Sources/GreekTvResources/playlists/m.tv.m3u8
  - id: ert_news
    title: Ert News
    epgId: ertnews
    pipeline:
      - type: url
        param: https://cbd537474fbad4634b64787657ff6456.msvdn.net/news/ert_news_main/mainabr/playlist_dvr.m3u8
  - id: riksat
    title: RikSat
    epgId: RIKsat.cy
    pipeline:
      - type: url
        param: https://l3.cloudskep.com/cybcsat/abr/playlist.m3u8
  - id: bluesky
    title: BlueSky
    epgId: bluesky
    pipeline:
      - type: url
        param: https://blueskytv.gr/live-tv/
      - type: source
      - type: css
        param:
          query: iframe
          selector:
            type: attribute
            value: src
      - type: regex
        param: (?<=video)\/.*(?=\?)
      - type: url
        param: https://www.dailymotion.com/player/metadata/video
      - type: source
      - type: json
        param: qualities.auto[0].url
  - id: euronews
    title: EuroNews
    epgId: EuroNews
    pipeline:
      - type: url
        param: https://gr.euronews.com/live
      - type: source
      - type: css
        param:
          query: ".u-aspect-ratio-16x9"
          selector:
            type: attribute
            value: data-video
      - type: json
        param: videoId
      - type: youtubeid
  - id: kontra
    title: Kontra
    epgId: kontra
    pipeline:
      - type: url
        param: https://kontralive.siliconweb.com/live/kontratv/playlist.m3u8
  - id: ertsports
    title: Ert Sports
    epgId: ertsports
    pipeline:
      - type: url
        param: https://cbd537474fbad4634b64787657ff6456.msvdn.net/sports1/ert_sports1_main/mainabr/playlist.m3u8?proxy
