timestamp: 2024-12-27 15:30:00 +2
epgsources:
  - url: https://github.com/KODIKAS-NL/GreekTv-epg/releases/download/EPG/epg.xml
    compression: none
channels:
  - id: ert1
    title: Ert 1
    epgId: ert1
    pipeline:
      - type: url
        param: http://192.168.1.52:10808/aHR0cHM6Ly9lcnRmbGl4LnMubGxud2kubmV0L2VydGxpdmUvZXJ0MS9jbHJkZWYyNDcyM2IvaW5kZXgubTN1OA==.m3u8
  - id: ert2
    title: Ert 2
    epgId: ert2
    pipeline:
      - type: url
        param: http://192.168.1.52:10808/aHR0cHM6Ly9lcnRmbGl4LnMubGxud2kubmV0L2VydGxpdmUvZXJ0Mi9jbHJkZWYyNDgyOHovaW5kZXgubTN1OA==.m3u8
  - id: ert3
    title: Ert 3
    epgId: ert3
    pipeline:
      - type: url
        param: http://192.168.1.52:10808/aHR0cHM6Ly9lcnRmbGl4LnMubGxud2kubmV0L2VydGxpdmUvZXJ0My9jbHJkZWYyNDgyOG4vaW5kZXgubTN1OA==.m3u8
  - id: skai
    title: Skai
    epgId: skai
    pipeline:
      - type: url
        param: https://skai-live-back.siliconweb.com/media/cambria4/index.m3u8
  - id: alpha
    title: Alpha
    epgId: alpha
    pipeline:
      - type: url
        param: https://www.alphatv.gr/webtv/live
      - type: source
      - type: regex
        param: https:\/\/.*m3u8
  - id: ant1
    title: Ant1
    epgId: ant1
    pipeline:
      - type: url
        param: http://l2.cloudskep.com/ant1cm2/abr/playlist.m3u8
  - id: mega
    title: mega
    epgId: mega
    pipeline:
      - type: url
        param: https://streamcdnh2-c98db5952cb54b358365984178fb898a.msvdn.net/live/S86713049/gonOwuUacAxM/playlist.m3u8
  - id: ertworld
    title: Ert World
    epgId: ertworld
    pipeline:
      - type: url
        param: https://ertflix.s.llnwi.net/ertlive/ertworld/default/index.m3u8
  - id: star
    title: Star
    epgId: star
    pipeline:
      - type: url
        param: https://www.star.gr/tv/live-stream/
      - type: source
      - type: regex
        param: https:.*\.m3u8
  - id: opentv
    title: opentv
    epgId: open
    pipeline:
      - type: url
        param: https://liveopencloud.siliconweb.com/1/ZlRza2R6L2tFRnFJ/eWVLSlQx/hls/live/playlist.m3u8
  - id: m.tv
    title: MacedoniaTV
    epgId: mtv
    pipeline:
      - type: url
        param: https://dlm34ll53zqql.cloudfront.net/out/v1/d4177931deff4c7ba994b8126d153d9f/maktv.m3u8
  - id: ert_news
    title: Ert News
    epgId: ertnews
    pipeline:
      - type: url
        param: http://192.168.1.52:10808/aHR0cHM6Ly9lcnRmbGl4LnMubGxud2kubmV0L2VydGxpdmUvZXJ0bmV3cy9kZWZhdWx0L2luZGV4Lm0zdTg=.m3u8
  - id: riksat
    title: RikSat
    epgId: RIKsat.cy
    pipeline:
      - type: url
        param: https://l3.cloudskep.com/cybcsat/abr/playlist.m3u8
  - id: bluesky
    title: BlueSky
    epgId: bluesky
    pipeline:
      - type: url
        param: https://blueskytv.gr/live-tv/
      - type: source
      - type: css
        param:
          query: ".svpPlayer"
          selector:
            type: attribute
            value: data-props
      - type: json
        param: "data.src"
  - id: euronews
    title: EuroNews
    epgId: EuroNews
    pipeline:
      - type: url
        param: https://gr.euronews.com/api/live/data?locale=el
      - type: source
      - type: json
        param: "videoPrimaryUrl"
  - id: kontra
    title: Kontra
    epgId: kontra
    pipeline:
      - type: url
        param: https://kontralive.siliconweb.com/live/kontratv/playlist.m3u8
