timestamp: 2025-07-05 13:57:00 +1
epgsources:
  - url: https://github.com/KODIKAS-NL/GreekTv-epg/releases/download/EPG/epg.xml
    compression: none
channels:
  - id: ert1
    title: Ert 1
    epgId: ert1
    pipeline:
      - type: url
        param: http://192.168.1.52:10808/aHR0cHM6Ly9lcnRmbGl4LmFrYW1haXplZC5uZXQvZXJ0bGl2ZS9lcnQxL2NscmRlZjI0NzIzYi9pbmRleC5tM3U4.m3u8
  - id: ert2
    title: Ert 2
    epgId: ert2
    pipeline:
      - type: url
        param: http://192.168.1.52:10808/aHR0cHM6Ly9lcnRmbGl4LmFrYW1haXplZC5uZXQvZXJ0bGl2ZS9lcnQyL2NscmRlZjI0ODI4ei9pbmRleC5tM3U4.m3u8
  - id: ert3
    title: Ert 3
    epgId: ert3
    pipeline:
      - type: url
        param: http://192.168.1.52:10808/aHR0cHM6Ly9lcnRmbGl4LmFrYW1haXplZC5uZXQvZXJ0bGl2ZS9lcnQzL2NscmRlZjI0ODI4bi9pbmRleC5tM3U4.m3u8
  - id: skai
    title: Skai
    epgId: skai
    pipeline:
      - type: url
        param: https://skai-live.siliconweb.com/media/cambria4/index.m3u8
  - id: alpha
    title: Alpha
    epgId: alpha
    pipeline:
      - type: url
        param: https://www.alphatv.gr/webtv/live
      - type: source
      - type: regex
        param: https:\/\/.*m3u8
  - id: ant1
    title: Ant1
    epgId: ant1
    pipeline:
      - type: url
        param: https://l2.cloudskep.com/ant1cm2/abr/playlist.m3u8
  - id: mega
    title: mega
    epgId: mega
    pipeline:
      - type: url
        param: https://streamcdng16-c98db5952cb54b358365984178fb898a.msvdn.net/live/S14373792/aGr5KG7RcZ9a/playlist.m3u8
  - id: ertworld
    title: Ert World
    epgId: ertworld
    pipeline:
      - type: url
        param: https://ertflix.akamaized.net/ertlive/ertworld/default/index.m3u8
  - id: star
    title: Star
    epgId: star
    pipeline:
      - type: url
        param: https://www.star.gr/tv/live-stream/
      - type: source
      - type: regex
        param: https:.*\.m3u8
  - id: opentv
    title: opentv
    epgId: open
    pipeline:
      - type: url
        param: https://liveopen.siliconweb.com/openTvLive/liveopen/playlist.m3u8
  - id: m.tv
    title: MacedoniaTV
    epgId: mtv
    pipeline:
      - type: url
        param: https://raw.githubusercontent.com/jimgate07/grtv/refs/heads/master/Metadoseis/maktv.m3u8
  - id: ert_news
    title: Ert News
    epgId: ertnews
    pipeline:
      - type: url
        param: https://ertflix.akamaized.net/ertlive/ertnews/default/index.m3u8
  - id: riksat
    title: RikSat
    epgId: RIKsat.cy
    pipeline:
      - type: url
        param: https://l3.cloudskep.com/cybcsat/abr/playlist.m3u8
  - id: bluesky
    title: BlueSky
    epgId: bluesky
    pipeline:
      - type: url
        param: https://blueskytv.gr/live-tv/
      - type: source
      - type: css
        param:
          query: ".svpPlayer"
          selector:
            type: attribute
            value: data-props
      - type: json
        param: "data.src"
  - id: euronews
    title: EuroNews
    epgId: EuroNews
    pipeline:
      - type: url
        param: https://gr.euronews.com/live
      - type: source
      - type: css
        param:
          query: .u-aspect-ratio-16x9
          selector:
            type: attribute
            value: data-video
      - type: json
        param: videoId
      - type: youtubeid
  - id: kontra
    title: Kontra
    epgId: kontra
    pipeline:
      - type: url
        param: https://kontralive.siliconweb.com/live/kontratv/playlist.m3u8
